name: unit-test
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        perl: [ '5.32', '5.30', '5.28' ]
        multi-thread: ["true", "false"]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }} with multithreaded ${{ matrix.multi-thread }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: apt-get install
        run:  |
          sudo apt-get install --no-install-recommends bioperl libdb-dev libberkeleydb-perl libxml-xpath-perl
      - name: dependency check
        run:  perl -MBio::SeqIO -e 1
      - run: cpanm --installdeps .
      - run: prove -lv t

